### ISSUE TITLE
Install fails with TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by brettgpalmer** [angstwad/docker.ubuntu#222]
Tried to install on ubuntu 14.04 but got a TypeError during the install. 

**Here is the information on my Virtual Box VM:**

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

**Here is the stack trace from the install:** 

ansible-galaxy install angstwad.docker_ubuntu
 downloading role 'docker_ubuntu', owned by angstwad
https://galaxy.ansible.com/roles/292/versions/?page=2&page_size=50
Traceback (most recent call last):
  File "/usr/bin/ansible-galaxy", line 814, in <module>
    main()
  File "/usr/bin/ansible-galaxy", line 808, in main
    fn(args, options, parser)
  File "/usr/bin/ansible-galaxy", line 687, in execute_install
    if len(role_versions) > 0:
TypeError: object of type 'NoneType' has no len()

Let me know if you need more information to reproduce this error.

**Comment by brettgpalmer** [comment]
Sorry just noticed the role require ansible 2.2.  I was running ansible 1.5.4.  I have upgrade my ansible now.
