### ISSUE TITLE
Install Docker-py failed

### ISSUE THREAD

**Issue by MrMMorris** [angstwad/docker.ubuntu#28]
Not sure if this is related to https://github.com/angstwad/docker.ubuntu/issues/27, but I hit this error during the Docker-py install:

```
{"cmd": "/usr/bin/pip install docker-py", "failed": true}
msg:
:stderr: Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
```

I was able to solve it by sshing in and running `easy_install -U pip` which upgraded to 6.0.8

**Comment by angstwad** [comment]
This is more of a python packaging problem than anything else.  :(. It is, BTW, unrelated to #27.

I suggest users that experience this issue regularly should create a pretask to upgrade pip.
