### ISSUE TITLE
Error at step "Install Docker-py"

### ISSUE THREAD

**Issue by edgrin** [angstwad/docker.ubuntu#34]
TASK: [angstwad.docker_ubuntu | Install Docker-py] **************************** 
failed: [default] => {"cmd": "/usr/bin/pip install docker-py", "failed": true}
msg: 
:stderr: Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
FATAL: all hosts have already failed -- aborting

After "easy_install -U pip" this error disappears:
http://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread

**Comment by edgrin** [comment]
https://github.com/angstwad/docker.ubuntu/issues/28
